export type EnFontType =
    | "h1"
    | "h2"
    | "h3"
    | "h4"
    | "subtitle1"
    | "subtitle2"
    | "subtitle3"
    | "body1"
    | "body2"
    | "body3"
    | "label"
    | "overline"
    // eslint-disable-next-line @typescript-eslint/ban-types
    | (string & {});
export type CnFontType =
    | "cH1"
    | "cH2"
    | "cH3"
    | "cH4"
    | "cH5"
    | "cH6"
    | "cH7"
    | "cSubtitle1"
    | "cSubtitle2"
    | "cSubtitle3"
    | "cSubtitle4"
    | "cSubtitle5"
    | "cBody1"
    | "cBody2"
    | "cBody3"
    | "cBody4"
    | "cLabel1"
    | "cLabel2"
    // eslint-disable-next-line @typescript-eslint/ban-types
    | (string & {});
