export const languageConfig = {
    CN: {
        "Start Time": "开始时间",
        January: "1月",
        February: "2月",
        March: "3月",
        April: "4月",
        May: "5月",
        June: "6月",
        July: "7月",
        August: "8月",
        September: "9月",
        October: "10月",
        November: "11月",
        December: "12月",
        SUN: "日",
        MON: "一",
        TUE: "二",
        WED: "三",
        THU: "四",
        FRI: "五",
        SAT: "六",
        AM: "上午",
        PM: "下午",
        Apply: "确定",
        Cancel: "取消",
        "No Time": "暂无时间",
        Now: "此刻",
    },
    EN: {
        "Start Time": "Start Time",
        January: "January",
        February: "February",
        March: "March",
        April: "April",
        May: "May",
        June: "June",
        July: "July",
        August: "August",
        September: "September",
        October: "October",
        November: "November",
        December: "December",
        SUN: "SUN",
        MON: "MON",
        TUE: "TUE",
        WED: "WED",
        THU: "THU",
        FRI: "FRI",
        SAT: "SAT",
        AM: "AM",
        PM: "PM",
        Apply: "Apply",
        Cancel: "Cancel",
        "No Time": "No Time",
        Now: "Now",
    },
};
