export const languageConfig = {
    CN: {
        "Related Documents": "附件",
        "Upload the related documentations with this project": "上传与项目相关的附件。",

        "Upload pictures": "上传图片",
        "Upload avatar": "上传头像",
        "Drop files here to upload or": "将文件拖拽到此处或",
        "choose file": "选择文件",
        "Not add any document yet": "还没有添加任何附件。",
        Loading: "加载中",

        "Please upload a picture": "请上传图片：大小",
        "pixels, and no larger than": "像素，且不能大于",
        Reset: "重新上传",
        Cancel: "取消",
        Confirm: "确定",
        "Drag or": "拖动或",
        browse: "浏览",
        "the picture to be uploaded here": "要上传的图片到这里",
        "Please check your image format, currently only supports":
            "请检查您上传的图片格式，目前仅支持",
        "type images": "格式的图片",
        "Please upload pictures below": "请上传",
        M: "M以下图片",
        preview: "预览",
    },
    EN: {
        "Related Documents": "Related Documents",
        "Upload the related documentations with this project":
            "Upload the related documentations with this project.",
        "Uploaded files": "Uploaded files",
        Loading: "Loading",
        preview: "Preview",
        "Upload pictures": "Upload pictures",
        "Upload avatar": "Upload avatar",
        "Drop files here to upload or": "Drop files here to upload or",
        "choose file": "choose file",
        "Not add any document yet": "Not add any document yet.",

        "Please upload a picture": "Please upload a picture: size ",
        "pixels, and no larger than": " pixels, and no larger than ",
        Reset: "Reset Upload",
        Cancel: "Cancel",
        Confirm: "Confirm",
        "Drag or": "Drag or ",
        browse: "browse",
        "the picture to be uploaded here": " the picture to be uploaded here",
        "Please check your image format, currently only supports":
            "Please check the format of the image you uploaded, currently only supports images in ",
        "type images": " format",
        "Please upload pictures below": "Please upload pictures below ",
        M: "M",
    },
};
