export const languageConfig = {
    CN: {
        Contacts: "联系人",
        "This email number already exists": "邮箱已存在",
        Error: "错误",
        "Email format error": "邮箱格式错误",
        "Name cannot be empty": "姓名不能为空",
        "Phone format error": "电话号码格式错误",
        "This mobile number already exists": "电话号码已被注册",
        "Phone cannot be empty": "电话号码不能为空",
        "Contact Info": "联系人信息",
        searchPlaceholder: "通过名称关键词搜索",
        Email: "邮箱",
        "Contact Email": "联系人邮箱",
        Name: "姓名",
        "Contact Name": "联系人姓名",
        Phone: "电话",
        "Contact Phone": "联系人电话",
        "Add Contact": "添加联系人",
        Save: "保存",
        Cancel: "取消",
        "Search by Name": "通过名字搜索",
        "His/Her Name": "他/她的姓名",
        "His/Her Email Address": "他/她的邮箱地址",
        Close: "关闭",
        nameError: {
            null: "请输入名称",
            repeat: "重复的名称",
        },
        emailError: {
            error: "邮箱错误",
        },
        PhoneError: {
            error: "手机号错误",
        },
        AddTips: "退出编辑后才可新增",
        null: "暂无相关联系人",
    },
    EN: {
        searchPlaceholder: "Search by Name",
        Contacts: "Contacts",
        "This email number already exists": "This email number already exists",
        Error: "Error",
        "Email format error": "Email format error",
        "Name cannot be empty": "Name cannot be empty",
        "Phone format error": "Phone format error",
        "This mobile number already exists": "This mobile number already exists",
        "Phone cannot be empty": "Phone cannot be empty",
        "Contact Info": "Contact Info",
        Email: "Email",
        "Contact Email": "Contact Email",
        Name: "Name",
        "Contact Name": "Contact Name",
        Phone: "Phone",
        "Contact Phone": "Contact Phone",
        "Add Contact": "Add Contact",
        Save: "Save",
        Cancel: "Cancel",
        "Search by Name": "Search by Name",
        "His/Her Name": "His/Her Name",
        "His/Her Email Address": "His/Her Email Address",
        Close: "Close",
        AddTips: "The addition can only be made after exiting the editing mode",
        nameError: {
            null: "Please enter a name",
            repeat: "The name is already taken",
        },
        emailError: {
            error: "Invalid email address",
        },
        PhoneError: {
            error: "Invalid phone number",
        },
        null: "No relevant contacts available",
    },
};
